routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', "HomeController@viewLanding");

//---------//
/* LOGIN */
//--------//
Route::get('/login', 'LoginController@viewLogin')->name('login');
Route::post('/login', 'LoginController@login');

Route::get('/reset', 'LoginController@viewPasswordReset');
Route::post('/reset', 'LoginController@passwordReset');

Route::get('/register', 'RegisterController@viewRegister');
Route::post('/register', 'RegisterController@register');

Route::post('/webhook', 'WebHookController@prueba');
//-----------//
/* END LOGIN*/
//-----------//

Route::group(['middleware' => 'auth'], function () {
	Route::get('/logout', 'LoginController@logout');
	Route::get('/logOptica', 'LoginController@logOptica');

	Route::get('/checkSuscripcion', 'SuscripcionController@checkSuscripcion');

	Route::get('/estadisticas', "IndexController@index");
	Route::get('/preguntas', "IndexController@showFaq");

	Route::group(['prefix' => 'cliente'], function () {
		Route::get('/', "UsuarioController@getCliente");

		Route::get('/{id}/receta/{producto_id}', "UsuarioController@showCliente");
		
		Route::get('/{id}/receta/{producto_id}/download', "RecetaController@downloadReceta");

		Route::post('/{id}/edit', "UsuarioController@editCreate");
		
		Route::post('/{id}/receta/{producto_id}/edit_receta', "RecetaController@update");
		
		Route::post('/save_mail', "UsuarioController@saveMail");
		Route::post('/send_mail', "UsuarioController@sendMail");
	});

	Route::post('/create_producto', "RecetaController@create");

	Route::get('/recetas', "RecetaController@getRecetas");
	Route::post('/recetas/{producto_id}/updateEstado', "RecetaController@updateEstado");

	Route::group(['prefix' => 'estadisticas'], function () {
		Route::get('/getRecetasByEstados', "EstadisticasController@getRecetasByEstados");
		Route::get('/getRecetasByMedico', "EstadisticasController@getRecetasByMedico");
		Route::get('/getInfoBoxes', "EstadisticasController@getInfoBoxes");
	});

	Route::group(['prefix' => 'administracion'], function () {
		Route::get('', "AdministracionController@show");
		Route::get('/save_profesional', "AdministracionController@saveProfesional");
		Route::post('/change_password', "AdministracionController@changePassword");

		Route::get('/medicos', "AdministracionController@showMedicos");
		Route::post('/medicos/save_medico', "AdministracionController@saveMedico");

		Route::get('/opticas', "AdministracionController@showOpticas");
		Route::post('/opticas/save_optica', "AdministracionController@saveOptica");
		
		Route::get('/usuarios', "AdministracionController@showUsuarios");
		Route::post('/usuarios/save_usuario', "AdministracionController@saveUsuario");
	});
	
	Route::group(['prefix' => 'suscripcion'], function () {
		Route::get('', "SuscripcionController@show");
		Route::post('asociarTarjeta', "SuscripcionController@asociarTarjeta");
		Route::post('deleteTarjeta', "SuscripcionController@deleteTarjeta");
		Route::post('updateDefaultTarjeta', "SuscripcionController@updateDefaultTarjeta");
		Route::post('editSuscripcion', "SuscripcionController@editSuscripcion");
	});

	Route::group(['prefix' => 'superadmin'], function () {
		Route::get('/', "SuperAdminController@show");
		Route::get('/notificaciones', "SuperAdminController@showNotificaciones");
		Route::get('/opticas', "SuperAdminController@showOpticas");
		Route::get('/planes', "SuperAdminController@showPlanes");
		Route::get('/getAdministradores', "SuperAdminController@getAdministradores");
		Route::get('/getAdministradoresByPago', "SuperAdminController@getAdministradoresByPago");
		Route::put('/planes', "SuperAdminController@savePlanes");
	});

	Route::get('/pruebaPdf', "PruebaController@pruebaPdf");

});

app/Optica.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class Optica extends Model{
	protected $table = 'optica';

    protected $fillable = [
        'nombre',
        'activo'
    ];

    public function getClientes(){
    	return $this->hasMany('App\Usuario', 'optica_id', 'id');
    }

    public function usuarios(){
        return $this->belongsToMany('App\Administrador', 'administrador_optica', 'optica_id', 'administrador_id');
    }

    public function productos(){
        return $this->hasMany('App\Producto', 'optica_id', 'id')->where('activo', 1);
    }

    public function profesionales(){
    	return $this->hasMany('App\Profesional', 'optica_id', 'id');
    }

    public function getMedicosIds(){
        $array = [];
        foreach ($this->profesionales as $prof) {
            array_push($array, $prof->id);
        }
        return $array;
    }

    public function puedeCrearUsuario(){
        $admin = $this->usuarios()->where('perfil_id', '1')->first();
        return $this->usuarios()->count() < $admin->plan()->first()->max_usuarios;
    }

    public function getCreatedAtAttribute($value){
        $dt = Carbon::parse($value);
        return $dt;
    }

}

app/Http/Controllers/SuperAdminController.php
<?php 

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Administrador;
use App\Notificar;
use App\Plan;
use App\Optica;
use App\TipoNotificacion;
use \Illuminate\Http\Request;
use App;
use Auth;
use Exception;
require_once base_path('vendor/mercadopago/sdk/lib/mercadopago.php');


class SuperAdminController extends Controller {

	public function show(){
		try {
			$admin = Auth::user();
			
			$response = view('superadmin.index', [
    			'rutas'     => [ 
                    ['url' => '/estadisticas', 'nombre' => 'Inicio'], 
                    ['url' => '/superadmin', 'nombre' => 'SuperAdmin', 'last' => true], 
                ],
                'admin'			=> $admin 
    		]);
		} catch (Exception $e) {
    		$response = $this->formatError($e);
		}

		return $response;
	}

	public function showNotificaciones(){
		try {
			$notificaciones = Notificar::orderBy('id')->get();
			$administrador = Auth::user();

			$response = view('superadmin.notificacionesList', [
    			'rutas'     => [ 
                    ['url' => '/estadisticas', 'nombre' => 'Inicio'], 
                    ['url' => '/superadmin', 'nombre' => 'SuperAdmin'], 
                    ['url' => '/notificaciones', 'nombre' => 'Notificaciones', 'last' => true], 
                ],
                'notificaciones'  => $notificaciones,
                'admin'			=> $administrador 
    		]);

		} catch (Exception $e) {
    		$response = $this->formatError($e);
		}

		return $response;
	}

	public function showPlanes(){
		try {
			$planes = Plan::orderBy('id')->get();
			$administrador = Auth::user();

			$mp = new \MP ( config('services.mercadopago.access_token') );
			
			$response = view('superadmin.planes', [
    			'rutas'     => [ 
                    ['url' => '/estadisticas', 'nombre' => 'Inicio'], 
                    ['url' => '/superadmin', 'nombre' => 'SuperAdmin'], 
                    ['url' => '/planes', 'nombre' => 'Planes', 'last' => true], 
                ],
                'planes'  => $planes,
                'admin'			=> $administrador 
    		]);

		} catch (Exception $e) {
    		$response = $this->formatError($e);
		}

		return $response;
	}

	public function showOpticas(){
		try {
			$opticas = Optica::withCount(['productos', 'getClientes'])->orderBy('id')->get();
			$administrador = Auth::user();

			$response = view('superadmin.opticas', [
    			'rutas'     => [ 
                    ['url' => '/estadisticas', 'nombre' => 'Inicio'], 
                    ['url' => '/superadmin', 'nombre' => 'SuperAdmin'], 
                    ['url' => '/planes', 'nombre' => 'Planes', 'last' => true], 
                ],
                'opticas'  => $opticas,
                'admin'		=> $administrador 
    		]);

		} catch (Exception $e) {
    		$response = $this->formatError($e);
		}

		return $response;
	}

	public function savePlanes( Request $request ){
		try {
			$planes = $request->all();
			$mp = new \MP ( config('services.mercadopago.access_token') );

			foreach ($planes as $plan_id => $value) {
				$plan = Plan::find( $plan_id );
				$plan->update( $value );

				if ( $plan->id_mp == '') {
					$plan_mp = $mp->post('/v1/plans/', 
						array( 
							'description' => $plan->nombre, 
							'auto_recurring' => [ 'frequency' => 1, 'frequency_type' => 'months', 'transaction_amount' => (int) $plan->monto ] 
						)
					);

					$plan->update([ 'id_mp' => $plan_mp['response']['id'] ]);
				}else{
					$plan_mp = $mp->get('/v1/plans/'.$plan->id_mp);
					$mp->put('/v1/plans/'.$plan->id_mp,['auto_recurring' => [ 'transaction_amount' => (int) $plan->monto ] ]);
				}
			}

			$response = json_encode([ 'error' => false ]);
		} catch (Exception $e) {
    		$response = $this->formatError($e);
		}
		return $response;
	}

	public function getAdministradores()
	{
		try {
			$administradores = Administrador::where('id', '!=', 1)->count();

			return [
					'clientes' => $administradores,
			];
		} catch (Exception $e) {
    		$response = $this->formatError($e);
		}
		return $response;
	}

	public function getAdministradoresByPago()
	{
		try {
			$administradores = Administrador::where('id', '!=', 1);

			return [
					'free' 		=> $administradores->where('suscripcion_mp', '=', '' )->count(),
					'premium' 	=> $administradores->where('suscripcion_mp', '!=', '' )->count(),
			];
		} catch (Exception $e) {
    		$response = $this->formatError($e);
		}
		return $response;
	}
}

resources/views/superadmin/index.blade.php
@extends('layout.layout')

@section('js')
    <script type="text/javascript" src="/js/superadmin/index.js"></script>
        <!-- Moment Plugin Js -->
    <script src="/plugins/momentjs/moment.js"></script>
    <script src="/plugins/momentjs/moment_locale_es.js"></script>

    <!-- Bootstrap Material Datetime Picker Plugin Js -->
    <script src="/plugins/daterangepicker/daterangepicker.js"></script>
    <link rel="stylesheet" type="text/css" href="/plugins/daterangepicker/daterangepicker.css">
    
    <script type="text/javascript">
        $(document).ready(function($) {
            var est = new SuperAdmin();
        });    
    </script>
@endsection

@section('content')
    <div class="crsf">
        {{ csrf_field() }}
    </div>
    <div class="container-fluid">
        <div class="row clearfix">
            <div class="card">
                <div class="header">
                    <h2 id="text">SUPER ADMIN</h2>
                </div>
                <div class="body">
                    <div class="row clearfix">
                        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                            <div class="info-box-4 bg-blue hover-expand-effect">
                                <div class="icon">
                                    <i class="material-icons">face</i>
                                </div>
                                <div class="content">
                                    <div class="text">CLIENTES</div>
                                    <div class="number count-to" id="infobox_clientes" data-from="0" data-to="0" data-speed="1000"></div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                            <div class="info-box-4 bg-green hover-expand-effect" onclick="location.href += '/planes'">
                                <div class="icon">
                                    <i class="material-icons">attach_money</i>
                                </div>
                                <div class="content">
                                    <div class="text">PLANES</div>
                                    <div class="number count-to" id="infobox_recetas" data-from="0" data-to="" data-speed="1000"></div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                            <div class="info-box-4 bg-red pointer hover-expand-effect" onclick="location.href += '/notificaciones'">
                                <div class="icon">
                                    <i class="material-icons">mail</i>
                                </div>
                                <div class="content">
                                    <div class="text">NOTIFICACIONES</div>
                                    <div class="number count-to" id="infobox_recetas" data-from="0" data-to="" data-speed="1000"></div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                            <div class="info-box-4 bg-purple pointer hover-expand-effect" onclick="location.href += '/opticas'">
                                <div class="icon">
                                    <i class="material-icons">business</i>
                                </div>
                                <div class="content">
                                    <div class="text">OPTICAS</div>
                                    <div class="number count-to" id="infobox_recetas" data-from="0" data-to="" data-speed="1000"></div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row clearfix">
                        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
                            <div class="card">
                                <div class="header bg-teal">
                                    <h2>RECETAS DE POR ESTADO</h2>
                                </div>
                                <div class="body">
                                    <div id="recetas_estado" class="dashboard-donut-chart"></div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
                            <div class="card">
                                <div class="header bg-teal">
                                    <h2>RECETAS DE POR PROFESIONAL</h2>
                                </div>
                                <div class="body">
                                    <div id="recetas_medico" class="dashboard-donut-chart"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/superadmin/notificacionesList.blade.php
@extends('layout.layout')

@section('content')
<div class="crsf">
    {{ csrf_field() }}
</div>
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <div class="row clearfix">
                    <div class="col-sm-3">
                        <h4>
                            NOTIFICACIONES
                        </h4>
                    </div>
                </div>
            </div>
            <div class="body">
                <div class="table-responsive" style="overflow-x: hidden !important;">
                    <table id="data-table-basic" class="table table-hover">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Tipo Notificacion</th>
                                <th>Administrador</th>
                                <th>Usuario</th>
                                <th>Created_at</th>
                            </tr>
                        </thead>
                        <tbody id="table-body">
                            @if( $notificaciones->count() == 0 )
                                <tr>
                                    <td>No hay notificaciones</td>
                                </tr>
                            @else
                                @foreach($notificaciones as $notificacion)
                                <tr>
                                    <td>{{ $notificacion->id }}</td>
                                    <td>{{ $notificacion->tipo_notificacion() }}</td>
                                    <td>{{ $notificacion->administrador()->mail }}</td>
                                    @if( !is_null( $notificacion->usuario_id ) )
                                        <td>{{ $notificacion->usuario()->mail }}</td>
                                    @else
                                        <td></td>
                                    @endif
                                    <td>{{ $notificacion->created_at }}</td>
                                </tr>
                                @endforeach
                            @endif
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('modals')

@endsection
@section('js')
    <!-- Jquery DataTable Plugin Js -->
    <script src="/plugins/jquery-datatable/jquery.dataTables.js"></script>
    <script src="/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js"></script>
    <script src="/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js"></script>
    <script src="/plugins/jquery-datatable/extensions/export/buttons.flash.min.js"></script>
    <script src="/plugins/jquery-datatable/extensions/export/jszip.min.js"></script>
    <script src="/plugins/jquery-datatable/extensions/export/pdfmake.min.js"></script>
    <script src="/plugins/jquery-datatable/extensions/export/vfs_fonts.js"></script>
    <script src="/plugins/jquery-datatable/extensions/export/buttons.html5.min.js"></script>
    <script src="/plugins/jquery-datatable/extensions/export/buttons.print.min.js"></script>

    <script type="text/javascript" src="/js/general/index.js"></script>
    <script type="text/javascript" src="/js/superadmin/index.js"></script>
    <script type="text/javascript"> // INIT
        $(document).ready(function() {
            var spa = new SuperAdmin();

            $("#data-table-basic").DataTable({
                "lengthMenu": [
                    [10, 25, 50, -1],
                    [10, 25, 50, "All"]
                ],
                dom: 'Bfrtip',
                buttons: [
                    {
                        extend: 'copyHtml5',
                        exportOptions: {
                            columns: [ 0, 1, 2, 3 ]
                        }
                    },
                    {
                        extend: 'excelHtml5',
                        exportOptions: {
                            columns: [ 0, 1, 2, 3 ]
                        }
                    },
                    {
                        extend: 'pdfHtml5',
                        exportOptions: {
                            columns: [ 0, 1, 2, 3 ]
                        }
                    },
                    {
                        extend: 'print',
                        exportOptions: {
                            columns: [ 0, 1, 2, 3 ]
                        }
                    },
                ],
                language: {
                    "lengthMenu": "Ver _MENU_ resultados",
                    "zeroRecords": "Ningun resultado encontrado",
                    "info": "Mostrando _PAGE_ de _PAGES_",
                    "infoEmpty": "Ningun resultado",
                    "search": "<b>BUSCAR:</b>",
                    "paginate": {
                        "first": "Primero",
                        "last": "Ultimo",
                        "next": "Sig",
                        "previous": "Ant"
                    },
                }
            });
        });
    </script>
@endsection

resources/views/superadmin/opticas.blade.php
@extends('layout.layout')

@section('content')
<div class="crsf">
    {{ csrf_field() }}
</div>
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <div class="row clearfix">
                    <div class="col-sm-3">
                        <h4>
                            OPTICAS
                        </h4>
                    </div>
                </div>
            </div>
            <div class="body">
                <div class="table-responsive" style="overflow-x: hidden !important;">
                    <table id="data-table-basic" class="table table-hover">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Nombre</th>
                                <th>Administrador</th>
                                <th>Clientes</th>
                                <th>Productos</th>
                                <th>Created_at</th>
                            </tr>
                        </thead>
                        <tbody id="table-body">
                            @if( $opticas->count() == 0 )
                                <tr>
                                    <td>No hay Opticas</td>
                                </tr>
                            @else
                                @foreach($opticas as $optica)
                                <tr>
                                    <td>{{ $optica->id }}</td>
                                    <td>{{ $optica->nombre }}</td>
                                    <td>{{ $optica->usuarios()->where('perfil_id', 1)->first()->mail }}</td>
                                    <td>{{ $optica->get_clientes_count }}</td>
                                    <td>{{ $optica->productos_count }}</td>
                                    <td>{{ $optica->created_at->format('Y-m-d') }}</td>
                                </tr>
                                @endforeach
                            @endif
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('modals')

@endsection
@section('js')
    <!-- Jquery DataTable Plugin Js -->
    <script src="/plugins/jquery-datatable/jquery.dataTables.js"></script>
    <script src="/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js"></script>
    <script src="/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js"></script>
    <script src="/plugins/jquery-datatable/extensions/export/buttons.flash.min.js"></script>
    <script src="/plugins/jquery-datatable/extensions/export/jszip.min.js"></script>
    <script src="/plugins/jquery-datatable/extensions/export/pdfmake.min.js"></script>
    <script src="/plugins/jquery-datatable/extensions/export/vfs_fonts.js"></script>
    <script src="/plugins/jquery-datatable/extensions/export/buttons.html5.min.js"></script>
    <script src="/plugins/jquery-datatable/extensions/export/buttons.print.min.js"></script>

    <script type="text/javascript" src="/js/general/index.js"></script>
    <script type="text/javascript" src="/js/superadmin/index.js"></script>
    <script type="text/javascript"> // INIT
        $(document).ready(function() {
            var spa = new SuperAdmin();

            $("#data-table-basic").DataTable({
                "lengthMenu": [
                    [10, 25, 50, -1],
                    [10, 25, 50, "All"]
                ],
                dom: 'Bfrtip',
                buttons: [
                    {
                        extend: 'copyHtml5',
                        exportOptions: {
                            columns: [ 0, 1, 2, 3 ]
                        }
                    },
                    {
                        extend: 'excelHtml5',
                        exportOptions: {
                            columns: [ 0, 1, 2, 3 ]
                        }
                    },
                    {
                        extend: 'pdfHtml5',
                        exportOptions: {
                            columns: [ 0, 1, 2, 3 ]
                        }
                    },
                    {
                        extend: 'print',
                        exportOptions: {
                            columns: [ 0, 1, 2, 3 ]
                        }
                    },
                ],
                language: {
                    "lengthMenu": "Ver _MENU_ resultados",
                    "zeroRecords": "Ningun resultado encontrado",
                    "info": "Mostrando _PAGE_ de _PAGES_",
                    "infoEmpty": "Ningun resultado",
                    "search": "<b>BUSCAR:</b>",
                    "paginate": {
                        "first": "Primero",
                        "last": "Ultimo",
                        "next": "Sig",
                        "previous": "Ant"
                    },
                }
            });
        });
    </script>
@endsection

resources/views/superadmin/planes.blade.php
@extends('layout.layout')

@section('content')
    <div class="crsf">
        {{ csrf_field() }}
    </div>
    <div class="container-fluid">
        <div class="row clearfix">
            <div class="card">
                <div class="header">
                    <div class="row clearfix">
                        <div class="col-sm-3">
                            <h4>
                                PLANES
                            </h4>
                        </div>
                    </div>
                </div>
                <div class="body">
                    <div class="row clearfix">
                        @foreach( $planes as $plan )
                            <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4 plan" id="{{ $plan->id }}">
                                <div class="card">
                                    <div class="header bg-blue">
                                        <h2>{{ $plan->nombre }}</h2>
                                    </div>
                                    <div class="body">
                                        <div class="row">
                                            <div class="col-lg-4">
                                                <div class="form-group">
                                                    <div class="form-group form-float">
                                                        <div class="form-line">
                                                            <label class="form-label">Max. Ópticas</label> 
                                                            <input class="form-control color" name="max_opticas" value="{{ $plan->max_opticas }}">
                                                        </div>                                  
                                                    </div>                                  
                                                </div>
                                            </div>
                                            <div class="col-lg-4">
                                                <div class="form-group">
                                                    <div class="form-group form-float">
                                                        <div class="form-line">
                                                            <label class="form-label">Max. Usuarios</label> 
                                                            <input class="form-control color" name="max_usuarios" value="{{ $plan->max_usuarios }}">
                                                        </div>                                  
                                                    </div>                                  
                                                </div>
                                            </div>
                                            <div class="col-lg-4">
                                                <div class="form-group">
                                                    <div class="form-group form-float">
                                                        <div class="form-line">
                                                            <label class="form-label">Monto</label> 
                                                            <input class="form-control color" name="monto" value="{{ $plan->monto }}">
                                                        </div>                                  
                                                    </div>                                  
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        @endforeach
                        <div class="row">
                            <div class="col-lg-4 col-lg-offset-4" style="display: flex;align-items: center;justify-content: center;">
                                <button type="button" id="save_planes" class="btn btn-lg bg-green waves-effect pull-left" style="background: #468e46">Guardar</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('js')
    <script type="text/javascript" src="/js/general/index.js"></script>
    <script type="text/javascript" src="/js/superadmin/index.js"></script>
    <script type="text/javascript"> // INIT
        $(document).ready(function() {
            var spa = new SuperAdmin();
        });
    </script>
@endsection